import { addBusinessMinutes, businessMinutesBetween, isOpenAt } from "./business-hours";
import { SLA_POLICIES, type PriorityValue } from "./policy";
import type { BusinessCalendar } from "./calendar";
export type SlaState = "ON_TRACK" | "AT_RISK" | "BREACHED" | "MET" | "PAUSED";
export type SlaClock = Readonly<{ dueAt: Date; atRiskAt: Date; eventAt: Date | null; eventMet: boolean | null }>;
export type SlaTicket = Readonly<{ priority: PriorityValue; createdAt: Date; firstResponseAt: Date | null; resolvedAt: Date | null; firstResponseSlaMet: boolean | null; resolutionSlaMet: boolean | null; firstResponseDueAt: Date; firstResponseAtRiskAt: Date; resolutionDueAt: Date; resolutionAtRiskAt: Date; slaPausedAt: Date | null; slaPausedMinutes: number }>;
export const computeTargets = (createdAt: Date, priority: PriorityValue, calendar: BusinessCalendar, pausedMinutes = 0): Readonly<{ firstResponseDueAt: Date; firstResponseAtRiskAt: Date; resolutionDueAt: Date; resolutionAtRiskAt: Date }> => { const policy = SLA_POLICIES[priority]; return { firstResponseDueAt: addBusinessMinutes(createdAt, policy.firstResponseMinutes + pausedMinutes, calendar), firstResponseAtRiskAt: addBusinessMinutes(createdAt, Math.floor(policy.firstResponseMinutes * .75) + pausedMinutes, calendar), resolutionDueAt: addBusinessMinutes(createdAt, policy.resolutionMinutes + pausedMinutes, calendar), resolutionAtRiskAt: addBusinessMinutes(createdAt, Math.floor(policy.resolutionMinutes * .75) + pausedMinutes, calendar) }; };
const state = (clock: SlaClock, now: Date, paused: boolean): SlaState => { if (clock.eventAt) return clock.eventMet ? "MET" : "BREACHED"; if (paused) return "PAUSED"; if (now >= clock.dueAt) return "BREACHED"; return now > clock.atRiskAt ? "AT_RISK" : "ON_TRACK"; };
export const evaluate = (ticket: SlaTicket, now: Date, calendar: BusinessCalendar) => { const effectiveNow = ticket.slaPausedAt ?? now; const policy = SLA_POLICIES[ticket.priority]; const firstResponseAt = ticket.firstResponseAt ?? effectiveNow; const resolvedAt = ticket.resolvedAt ?? effectiveNow; return { firstResponseDueAt: ticket.firstResponseDueAt, resolutionDueAt: ticket.resolutionDueAt, firstResponseState: state({ dueAt: ticket.firstResponseDueAt, atRiskAt: ticket.firstResponseAtRiskAt, eventAt: ticket.firstResponseAt, eventMet: ticket.firstResponseSlaMet }, effectiveNow, Boolean(ticket.slaPausedAt)), resolutionState: state({ dueAt: ticket.resolutionDueAt, atRiskAt: ticket.resolutionAtRiskAt, eventAt: ticket.resolvedAt, eventMet: ticket.resolutionSlaMet }, effectiveNow, Boolean(ticket.slaPausedAt)), firstResponseRemainingMinutes: policy.firstResponseMinutes + ticket.slaPausedMinutes - businessMinutesBetween(ticket.createdAt, firstResponseAt, calendar), resolutionRemainingMinutes: policy.resolutionMinutes + ticket.slaPausedMinutes - businessMinutesBetween(ticket.createdAt, resolvedAt, calendar), isBusinessHoursOpen: isOpenAt(now, calendar) }; };
