import { Shell } from "../../../components/shell";
import { api } from "../../../lib/api";
import { getToken } from "../../../lib/session";
import { TicketActions } from "../../../components/ticket-actions";
import { SlaCountdown } from "../../../components/sla-countdown";
import { TicketCommentForm } from "../../../components/ticket-comment-form";

type Detail = Readonly<{ me: { id: string; role: string } | null; ticket: { id: string; reference: number; title: string; description: string; priority: string; status: string; createdAt: string; reporter: { name: string; email: string }; assignee: { id: string; name: string } | null; sla: { firstResponseDueAt: string; resolutionDueAt: string; firstResponseState: string; resolutionState: string; firstResponseRemainingMinutes: number; resolutionRemainingMinutes: number; isBusinessHoursOpen: boolean }; comments: readonly { id: string; content: string; createdAt: string; author: { name: string } }[]; events: readonly { id: string; type: string; createdAt: string; actor: { name: string } }[] }; users: readonly { id: string; name: string }[] }>;
const query = `query($id:ID!){me{id role} ticket(id:$id){id reference title description priority status createdAt reporter{name email} assignee{id name} sla{firstResponseDueAt resolutionDueAt firstResponseState resolutionState firstResponseRemainingMinutes resolutionRemainingMinutes isBusinessHoursOpen} comments{id content createdAt author{name}} events{id type createdAt actor{name}}} users(role:AGENT){id name}}`;
const format = (value: string): string => new Date(value).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });
const slaClass = (state: string): string => ({ ON_TRACK: "track", AT_RISK: "risk", BREACHED: "breach", MET: "track", PAUSED: "waiting" })[state] ?? "track";

export default async function TicketDetail({ params }: Readonly<{ params: Promise<{ id: string }> }>) {
  const { id } = await params;
  let data: Detail | null = null;
  try { data = await api<Detail>(query, { id }, await getToken()); } catch { }
  const ticket = data?.ticket;
  if (!ticket) return <Shell><section className="panel"><div className="empty">This ticket could not be found or you do not have access to it.</div></section></Shell>;
  const isAgent = data?.me?.role === "AGENT";
  return <Shell><header className="top"><div><div className="eyebrow">Ticket #{ticket.reference} · {ticket.priority}</div><h1 className="title">{ticket.title}</h1></div><span className="badge progress">{ticket.status.replaceAll("_", " ")}</span></header><div className="detail"><div><section className="card"><h3>Request</h3><p className="description">{ticket.description}</p><p className="muted">Raised by {ticket.reporter.name} · {format(ticket.createdAt)}</p></section><section className="card" style={{ marginTop: 18 }}><h3>Conversation</h3>{ticket.comments.length ? ticket.comments.map((comment) => <article className="comment" key={comment.id}><strong>{comment.author.name}</strong><span className="sub"> · {format(comment.createdAt)}</span><p className="description">{comment.content}</p></article>) : <p className="muted">No comments yet.</p>}<TicketCommentForm ticketId={ticket.id} agentMode={isAgent}/></section></div><aside><section className="card"><h3>SLA health</h3><div className="sla-row"><div className="sub">First response</div><span className={`badge ${slaClass(ticket.sla.firstResponseState)}`}>{ticket.sla.firstResponseState.replaceAll("_", " ")}</span><strong><SlaCountdown minutes={ticket.sla.firstResponseRemainingMinutes} isBusinessHoursOpen={ticket.sla.isBusinessHoursOpen} state={ticket.sla.firstResponseState}/></strong><div className="sub">Due {format(ticket.sla.firstResponseDueAt)}</div></div><div className="sla-row"><div className="sub">Resolution</div><span className={`badge ${slaClass(ticket.sla.resolutionState)}`}>{ticket.sla.resolutionState.replaceAll("_", " ")}</span><strong><SlaCountdown minutes={ticket.sla.resolutionRemainingMinutes} isBusinessHoursOpen={ticket.sla.isBusinessHoursOpen} state={ticket.sla.resolutionState}/></strong><div className="sub">Due {format(ticket.sla.resolutionDueAt)}</div></div></section><section className="card" style={{ marginTop: 18 }}><h3>Ownership</h3><p className="muted">Reporter</p><strong>{ticket.reporter.name}</strong><p className="muted">Assignee</p><strong>{ticket.assignee?.name ?? "Unassigned"}</strong></section>{isAgent && data?.me ? <TicketActions ticketId={ticket.id} status={ticket.status} assigneeId={ticket.assignee?.id ?? null} currentAgentId={data.me.id} agents={data.users}/> : <section className="card" style={{ marginTop: 18 }}><h3>Ticket updates</h3><p className="muted">An agent can claim this request, update its status, and add a response here.</p></section>}<section className="card" style={{ marginTop: 18 }}><h3>Activity</h3>{ticket.events.slice(0, 5).map((event) => <p className="muted" key={event.id}>{event.actor.name} · {event.type.replaceAll("_", " ")}</p>)}</section></aside></div></Shell>;
}
